### ISSUE TITLE
[PE-D][Tester B] Example commands for Filter function not working as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W11-2/tp#130]
The following command is listed in the UG as an example for the **Filter** function:

![image.png](https://raw.githubusercontent.com/lihaoquan/ped/main/files/a4a84d93-e164-4d25-b6bf-dafba28b5bac.png)

However, when copy and pasting `filter NUS Cycling`, the application output the following error:

![image.png](https://raw.githubusercontent.com/lihaoquan/ped/main/files/c1f5ecb3-01e1-4922-af56-3c3df111fc58.png)

The initial sample data does have people belonging to the `NUS Cycling` CCA, which are the contacts that were expected to be listed when running the `filter NUS Cycling` command.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lihaoquan/ped#2

**Comment by chuahjiajie** [comment]
Fixed in the UG already. Proper format has been stated to require c/ or r/
