### ISSUE TITLE
[PE-D][Tester A] Filter command in UG is wrong

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W11-2/tp#135]
![Screenshot 2024-04-05 at 4.27.07 PM.png](https://raw.githubusercontent.com/Bandov/ped/main/files/4a197887-48e3-48c3-9a0a-46e9dc406140.png)
Steps to reproduce:
filter CCA

Expected:
error message showing that the flag is missing

Actual:
I used the method shown on the UG. And it gives me the error where i have not provided a CCA

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Bandov/ped#5

**Comment by Fidget-Spinner** [comment]
Fixed by https://github.com/AY2324S2-CS2103T-W11-2/tp/pull/198
