### ISSUE TITLE
[PE-D][Tester D] Incorrect command format in "Filter by CCA"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W11-2/tp#136]
![image.png](https://raw.githubusercontent.com/ronnnnnnnnn/ped/main/files/49b5ecd8-2b2b-4eaf-90c8-b691e03dd4d8.png)

The correct command format should be `filter c/NUS Cycling`. However, the example command in the screenshot does not include the prefix `c/`.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ronnnnnnnnn/ped#4

**Comment by Fidget-Spinner** [comment]
fixed by https://github.com/AY2324S2-CS2103T-W11-2/tp/pull/198
