### ISSUE TITLE
[PE-D][Tester D] Same information included in the "Tutorial" and "Reference" sections

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W11-2/tp#140]
This is a minor nitpick, but I noticed that the commands from `owe` onwards have the same information in both Tutorial and Reference in the UG. Perhaps the ones in Tutorial can be changed to include example usages and screenshots like the rest of the commands in Tutorial.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ronnnnnnnnn/ped#5

**Comment by chuahjiajie** [comment]
Revamped UG no longer relevant
