### ISSUE TITLE
[PE-D][Tester D] Roles should be limited to those found in CCAs

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W11-2/tp#174]
This is somewhat related to issue #2 and is also a little bit nitpicky. Quoting from the UG, "CCA Manager is a **contact manager designed to simplify the management of CCAs and enhance your administrative efficiency**". Since CCA management is the main concern and the app is not meant to be a personal address book, I don't think roles such as `friends`, `colleagues` and `family` are really relevant to the product.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ronnnnnnnnn/ped#13

**Comment by JuliaPoo** [comment]
This is invalid, sorry. But we do not anticipate the kind of roles in a CCA for good reasons.
