### ISSUE TITLE
[Epic] Update the user guide

### ISSUE THREAD

**Issue by Fidget-Spinner** [AY2324S2-CS2103T-W11-2/tp#62]
User guide needs to be more user focused
- [x] #63
- [x] #64
- [x] #65
- [x] #66
- [x] #67

**Comment by JuliaPoo** [comment]
Overall plan (feel free to edit):

1. Introduction
    - What this software is about
    - Problem we're trying to solve
    - How the software solves the problem
    - Links to basic tutorials (concrete use cases)
2. Basic setup
2. Basic tutorials
3. Reference section
    - Feature List
4. What's New
5. Upcoming Features
