### ISSUE TITLE
[Epic] A better intro that catches the user attention, and assumes less of what the user should already know

### ISSUE THREAD

**Issue by Fidget-Spinner** [AY2324S2-CS2103T-W11-2/tp#63]
- [ ] Table of Contents
   - [x] #70
   - [x] #69
   - [x] #68

More details [here](https://github.com/AY2324S2-CS2103T-W11-2/tp/issues/62#issuecomment-2016795195)

**Comment by JuliaPoo** [comment]
This is massive, prolly need to split this up.
