### ISSUE TITLE
Unable to change CCA label using edit command

### ISSUE THREAD

**Issue by LifHoshi** [AY2324S2-CS2103T-W11-2/tp#87]
If I want to change the cca labeling using the edit command, it won't work. But others work well.
<img width="710" alt="image" src="https://github.com/AY2324S2-CS2103T-W11-2/tp/assets/147591205/d8820961-9a01-4bdb-bb35-ffe5306ccad0">

**Comment by JuliaPoo** [comment]
Oh oops I fixed this in my branch alr

**Comment by LifHoshi** [comment]
> Oh oops I fixed this in my branch alr. Will push soon since nobody is working on anything else for now.
> 
> Im fixing a bunch of issues at once
