### ISSUE TITLE
Both edit t/tag and assign command could change the role

### ISSUE THREAD

**Issue by LifHoshi** [AY2324S2-CS2103T-W11-2/tp#89]
<img width="739" alt="Screenshot 2024-03-28 at 16 11 10" src="https://github.com/AY2324S2-CS2103T-W11-2/tp/assets/147591205/0c1c63e9-9f3e-46dc-bfad-814d9f4b0ba7">
<img width="741" alt="Screenshot 2024-03-28 at 16 12 50" src="https://github.com/AY2324S2-CS2103T-W11-2/tp/assets/147591205/02248f26-644d-4733-bd47-dfd850f9ee1b">

So, I'm not sure whether to keep this feature for simplicity or fix it.

**Comment by JuliaPoo** [comment]
Isn't it because internally, `tags` are roles? I'm tryna fix this in #93
