### ISSUE TITLE
Target user profile, value proposition, and user stories

### ISSUE THREAD

**Issue by chuahjiajie** [AY2324S2-CS2103T-W11-2/tp#9]
Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.

**Comment by alphajae11** [comment]
Should be closed based on #14

**Comment by alphajae11** [comment]
Should be closed based on https://github.com/AY2324S2-CS2103T-W11-2/tp/pull/14
